---
contentdir: "src"
layoutdir: "layouts"
publishdir: "_build/public"
indexes:
  category: "categories"
baseurl: "https://sbinet.github.io"
title: "0xb1ns>> go run"
theme: "purehugo"
canonifyurls: true

# enable pygments (but use Chroma)
pygmentsCodeFencesGuessSyntax: true
pygmentsUseClasses: true
pygmentsUseClassic: false
#pygmentsCodeFences: true

params:
    author: "Sebastien Binet"
    twitterName: "0xb1ns"
    githubName: "sbinet"
    description: "Digital ramblings of a french gopher"
    hideShareOptions: true
...

